# Get All Data Coffees
# GET http://localhost:3000/api/coffees/

# Get Data Coffee By Id
# GET http://localhost:3000/api/coffees/1

# Post New Data Coffee
# POST http://localhost:3000/api/coffees/new-coffee
# Content-Type: application/json

# {
#     "name": "Kopi ABC",
#     "origin": "Indonesia",
#     "type": "Indonesian",
#     "flavor_profile": "delicious and steady",
#     "price": 2500
# }

# Get Data Coffee By Id
# GET http://localhost:3000/api/coffees/Specialty

# Update/Put Data Coffee By Id
PUT  http://localhost:3000/api/coffees/3
Content-Type: application/json

{
    "name": "Kopi Luwak Mantap",
    "origin": "Indonesia",
    "type": "Specialty",
    "flavor_profile": "Khas Indonesia",
    "price": 100000
}